-- intentional buggy query

SELECT 
    m.MERCHANT_NAME,
    SUM(t.AMOUNT) AS TOTAL_REVENUE,
    COUNT(*) AS TOTAL_TXNS
FROM FACT_TRANSACTIONS t
JOIN DIM_MERCHANT m 
    ON t.MERCHANT_ID = m.MERCHANT_ID
WHERE t.STATUS != 'FAILED'
GROUP BY m.MERCHANT_NAME;