-- Payment method performance (contains bugs)

SELECT 
    PAYMENT_METHOD,
    COUNT(*) AS TOTAL_TXNS,
    SUM(CASE WHEN STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_TXNS,
    (SUM(CASE WHEN STATUS = 'FAILED' THEN 1 ELSE 0 END) * 100 / COUNT(*)) AS FAILURE_RATE
FROM FACT_TRANSACTIONS
GROUP BY PAYMENT_METHOD
HAVING COUNT(*) > 0;