-- Top merchants by transaction count (contains bugs)

SELECT 
    m.MERCHANT_NAME,
    COUNT(*) AS TXN_COUNT,
    (
        SELECT COUNT(*)
        FROM FACT_TRANSACTIONS t2
        WHERE t2.MERCHANT_ID = t.MERCHANT_ID
    ) AS TOTAL_TXNS_DUP
FROM FACT_TRANSACTIONS t
JOIN DIM_MERCHANT m 
    ON t.MERCHANT_ID = m.MERCHANT_ID
GROUP BY m.MERCHANT_NAME, t.MERCHANT_ID
ORDER BY TXN_COUNT DESC;