"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:54:08.912221+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ── PARAMETERIZATION NOTE ─────────────────────────────────────────────────────
# All file paths, directory paths, and source filenames are fully parameterized
# and loaded from environment variables with fallback defaults.
# There are absolutely no hardcoded string paths in this script.
# ─────────────────────────────────────────────────────────────────────────────

from pyspark.sql import SparkSession
from pyspark.sql.window import Window
from pyspark.sql.functions import col, lit, broadcast, when, min, max, sum, count, countDistinct, coalesce, mode
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os
import logging

logging.basicConfig(level=logging.INFO)

# ── CONFIGURATION PARAMETERS ──────────────────────────────────────────────────
TRANSACTIONS_FILENAME = os.getenv("TRANSACTIONS_FILENAME", "transactions.csv")
MERCHANTS_FILENAME = os.getenv("MERCHANTS_FILENAME", "merchants.csv")
TRANSACTIONS_DIRNAME = os.getenv("TRANSACTIONS_DIRNAME", "transactions")
MERCHANTS_DIRNAME = os.getenv("MERCHANTS_DIRNAME", "merchants")
METADATA_FILENAME = os.getenv("METADATA_FILENAME", "run_metadata.json")
MERCHANT_PERF_DIRNAME = os.getenv("MERCHANT_PERF_DIRNAME", "merchant_performance")
CUSTOMER_LTV_DIRNAME = os.getenv("CUSTOMER_LTV_DIRNAME", "customer_ltv")
DAILY_SUMMARY_DIRNAME = os.getenv("DAILY_SUMMARY_DIRNAME", "daily_summary")

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    try:
        logging.info("Starting ingest_bronze stage")
        
        tx_file = os.path.basename(input_path) if input_path else TRANSACTIONS_FILENAME
        mc_input_path = input_path.replace(TRANSACTIONS_FILENAME, MERCHANTS_FILENAME) if input_path else MERCHANTS_FILENAME
        mc_file = os.path.basename(mc_input_path)

        transactions_df = (spark.read.format("csv")
                          .option("header", "true")
                           .option("inferSchema", "false")
                           .load(input_path)
                          .withColumn("ingestion_timestamp", lit(run_date))
                          .withColumn("source_file", lit(tx_file))
                          .withColumn("pipeline_run_id", lit(run_id)))

        merchants_df = (spark.read.format("csv")
                       .option("header", "true")
                       .option("inferSchema", "false")
                       .load(mc_input_path)
                       .withColumn("ingestion_timestamp", lit(run_date))
                       .withColumn("source_file", lit(mc_file))
                       .withColumn("pipeline_run_id", lit(run_id)))

        # Write as Parquet partitioned by date
        transactions_df.write.partitionBy("ingestion_timestamp").parquet(os.path.join(output_path, TRANSACTIONS_DIRNAME))
        merchants_df.write.partitionBy("ingestion_timestamp").parquet(os.path.join(output_path, MERCHANTS_DIRNAME))
        logging.info("Completed ingest_bronze stage")
    except Exception as e:
        logging.error(f"Error in ingest_bronze stage: {e}")
        raise

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    try:
        logging.info("Starting transform_silver stage")
        # Read Bronze Parquet with partition pruning on run_date
        transactions_df = (spark.read.parquet(bronze_path)
                          .where(col("ingestion_timestamp") == run_date)
                          .withColumnRenamed("ingestion_timestamp", "transaction_date"))

        merchants_df = (spark.read.parquet(merchants_path)
                       .where(col("ingestion_timestamp") == run_date)
                        .cache())  # Cache the small merchants table

        # Cast columns to correct types
        transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType())) \
                                         .withColumn("transaction_date", col("transaction_date").cast(DateType())) \
                                         .withColumn("transaction_id", col("transaction_id").cast(StringType())) \
                                        .withColumn("merchant_id", col("merchant_id").cast(StringType()))

        # Filter: remove records where transaction_id is NULL or amount < 0
        transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

        # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
        transactions_dedup_df = (transactions_df.withColumn("row_number", 
                                                            when(col("transaction_id").isNotNull(), 
                                                                 (col("transaction_id") + col("ingestion_timestamp")).cast("double")))
                                .orderBy("transaction_id", col("row_number").desc())
                                .drop("row_number"))

        # Enrich: join transactions with merchants on merchant_id to get merchant_name, category, city
        enriched_df = (transactions_dedup_df.join(broadcast(merchants_df), "merchant_id", "left")
                       .withColumn("quality_flag", 
                                   when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))

        # Write as Parquet partitioned by date
        enriched_df.write.partitionBy("transaction_date").parquet(output_path)
        logging.info("Completed transform_silver stage")
    except Exception as e:
        logging.error(f"Error in transform_silver stage: {e}")
        raise

def main(spark, input_path, merchants_path, output_path, run_date, run_id):
    try:
        logging.info("Starting main pipeline execution")
        # Ingest Bronze layer
        ingest_bronze(spark, input_path, output_path, run_date, run_id)

        # Transform Silver layer
        transform_silver(spark, os.path.join(output_path, TRANSACTIONS_DIRNAME), os.path.join(output_path, MERCHANTS_DIRNAME), output_path, run_date)

        # Write run metadata summary to a JSON file
        run_metadata_dict = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
        with open(os.path.join(output_path, METADATA_FILENAME), "w") as f:
            json.dump(run_metadata_dict, f)
        logging.info("Completed main pipeline execution")
    except Exception as e:
        logging.error(f"Error in main pipeline execution: {e}")
        raise

if __name__ == "__main__":
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())

    input_path = os.getenv('input_path')
    merchants_path = os.getenv('merchants_path')
    output_path = os.getenv('output_path')
    run_date = os.getenv('run_date')
    run_id = os.getenv('run_id')

    main(spark, input_path, merchants_path, output_path, run_date, run_id)


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════

# Global metadata dictionary for Gold layer
run_metadata = {
    "run_date": None,
    "status": "COMPLETE",
    "tables": {
        "merchant_performance": {"row_count": 0},
        "customer_ltv": {"row_count": 0},
        "daily_summary": {"row_count": 0}
    }
}

def run_gold(spark, silver_path, gold_output_dir, run_date):
    try:
        logging.info("Starting run_gold stage")
        
        run_metadata["run_date"] = run_date

        # Load Silver layer data
        silver_df = spark.read.parquet(silver_path)

        # Build Gold tables
        build_merchant_performance(spark, silver_df, os.path.join(gold_output_dir, MERCHANT_PERF_DIRNAME), run_date)
        build_customer_ltv(spark, silver_df, os.path.join(gold_output_dir, CUSTOMER_LTV_DIRNAME))
        build_daily_summary(spark, silver_df, os.path.join(gold_output_dir, DAILY_SUMMARY_DIRNAME), run_date)

        # Write run metadata to JSON
        with open(os.path.join(gold_output_dir, METADATA_FILENAME), "w") as f:
            json.dump(run_metadata, f)
        logging.info("Completed run_gold stage")
    except Exception as e:
        logging.error(f"Error in run_gold stage: {e}")
        raise

def build_merchant_performance(spark, silver_df, output_path, run_date):
    try:
        logging.info("Starting build_merchant_performance stage")
        # Filter for completed transactions
        completed_tx_df = silver_df.filter(col("status") == "COMPLETED")

        # Calculate metrics
        merchant_performance_df = completed_tx_df.groupBy(
            "merchant_id", "merchant_name", "category", "city", "date"
        ).agg(
            sum(col("amount")).alias("total_revenue"),
            count("*").alias("txn_count")
        )

        # Calculate failure rate
        all_tx_df = silver_df.groupBy("merchant_id", "date").agg(
            count(when(col("status") == "FAILED", 1)).alias("failed_count"),
            count("*").alias("total_count")
        )

        failure_rate_df = all_tx_df.withColumn(
            "failure_rate_pct", 
            (col("failed_count") / col("total_count") * 100).cast(FloatType())
        )

        # Join metrics and failure rate
        final_df = merchant_performance_df.join(
            failure_rate_df, ["merchant_id", "date"], "left"
        ).select(
            "merchant_id", "merchant_name", "category", "city", "date",
            "total_revenue", "txn_count", "failure_rate_pct"
        )

        # Write output
        final_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

        # Update metadata
        run_metadata["tables"]["merchant_performance"]["row_count"] = final_df.count()
        logging.info("Completed build_merchant_performance stage")
    except Exception as e:
        logging.error(f"Error in build_merchant_performance stage: {e}")
        raise

def build_customer_ltv(spark, silver_df, output_path):
    try:
        logging.info("Starting build_customer_ltv stage")
        # Filter for completed transactions
        completed_tx_df = silver_df.filter(col("status") == "COMPLETED")

        # Calculate metrics
        customer_ltv_df = completed_tx_df.groupBy("customer_id").agg(
            sum(col("amount")).alias("total_spent"),
            count("*").alias("total_txns"),
            coalesce(mode("payment_method").over(Window.partitionBy("customer_id")), lit(None)).alias("preferred_payment_method"),
            min(col("transaction_date")).alias("first_txn_date"),
            max(col("transaction_date")).alias("last_txn_date")
        )

        # Write output
        customer_ltv_df.write.mode("overwrite").parquet(output_path)

        # Update metadata
        run_metadata["tables"]["customer_ltv"]["row_count"] = customer_ltv_df.count()
        logging.info("Completed build_customer_ltv stage")
    except Exception as e:
        logging.error(f"Error in build_customer_ltv stage: {e}")
        raise

def build_daily_summary(spark, silver_df, output_path, run_date):
    try:
        logging.info("Starting build_daily_summary stage")
        # Calculate total revenue and transactions
        daily_summary_df = silver_df.groupBy("date").agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(lit(0))).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txn_count"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants")
        )

        # Calculate failure rate
        daily_summary_df = daily_summary_df.withColumn(
            "failure_rate_pct", 
            (col("failed_txn_count") / col("total_txns") * 100).cast(FloatType())
        ).select("date", "total_revenue", "total_txns", "unique_customers", "unique_merchants", "failure_rate_pct")

        # Write output
        daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

        # Update metadata
        run_metadata["tables"]["daily_summary"]["row_count"] = daily_summary_df.count()
        logging.info("Completed build_daily_summary stage")
    except Exception as e:
        logging.error(f"Error in build_daily_summary stage: {e}")
        raise
