"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:52:59.592344+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, lit, broadcast, when
from pyspark.sql.types import DoubleType, StringType, TimestampType, DateType

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read CSV with all columns as strings
    bronze_df = spark.read.format("csv").option("header", "true").load(input_path)
    
    # Add ingestion_timestamp, source_file, pipeline_run_id columns
    bronze_df = bronze_df.withColumn("ingestion_timestamp", current_timestamp()) \
                         .withColumn("source_file_path", lit(input_path)) \
                        .withColumn("pipeline_run_id", lit(run_id))
    
    # Cast transaction_timestamp to TimestampType
    bronze_df = bronze_df.withColumn("transaction_timestamp", col("transaction_timestamp").cast(TimestampType()))
    
    # Partition by transaction_date
    transaction_date = (bronze_df["transaction_timestamp"].cast(DateType()).alias("transaction_date"))
    bronze_df = bronze_df.withColumn("transaction_date", transaction_date)
    
    # Write Parquet partitioned by date
    bronze_df.write.partitionBy("transaction_date").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    bronze_df = spark.read.parquet(bronze_path).where(col("transaction_date") == run_date)
    
    # Cast columns to correct types
    bronze_df = bronze_df.withColumn("amount", col("amount").cast(DoubleType())) \
                         .withColumn("transaction_timestamp", col("transaction_timestamp").cast(TimestampType())) \
                        .withColumn("transaction_id", col("transaction_id").cast(StringType())) \
                        .withColumn("customer_id", col("customer_id").cast(StringType()))
    
    # Filter NULL transaction_id and negative amounts
    bronze_df = bronze_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    latest_transactions = bronze_df.groupBy("transaction_id").agg(
        {"transaction_id": "first", 
         "customer_id": "first", 
         "amount": "first", 
         "payment_method": "first", 
         "status": "first", 
         "transaction_timestamp": "max", 
         "ingestion_timestamp": "first", 
         "source_file_path": "first", 
         "pipeline_run_id": "first", 
         "transaction_date": "first"}
    ).withColumnRenamed("max(transaction_timestamp)", "transaction_timestamp")
    
    # Read merchants data and cache it
    merchants_df = spark.read.parquet(merchants_path)
    merchants_df = broadcast(merchants_df)
    merchants_df.cache()
    
    # Join with merchants
    silver_df = latest_transactions.join(merchants_df, "customer_id", "left")
    
    # Add quality_flag column (CLEAN or UNMATCHED)
    silver_df = silver_df.withColumn("quality_flag", 
                                     when(col("customer_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Write Parquet partitioned by date
    silver_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Create Spark session
    spark = SparkSession.builder.appName("TransactionAuditPipeline").getOrCreate()
    
    # Define paths and run date
    input_path = "s3://path/to/bronze/transactions"
    bronze_path = "s3://path/to/bronze/transactions"
    merchants_path = "s3://path/to/merchants"
    silver_output_path = "s3://path/to/silver/transactions"
    run_date = "2023-10-01"
    run_id = "run_id_12345"
    
    # Ingest bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform to silver layer
    transform_silver(spark, bronze_path, merchants_path, silver_output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, expr, current_timestamp, coalesce, when
from pyspark.sql.types import StructType, StructField, DoubleType, StringType, TimestampType, IntegerType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("status") == "COMPLETED")
    
    # Define schema for merchant performance
    merchant_performance_schema = StructType([
        StructField("merchant_id", StringType(), True),
        StructField("merchant_name", StringType(), True),
        StructField("category", StringType(), True),
        StructField("city", StringType(), True),
        StructField("date", TimestampType(), True),
        StructField("total_revenue", DoubleType(), True),
        StructField("txn_count", IntegerType(), True),
        StructField("failure_rate_pct", DoubleType(), True)
    ])
    
    # Calculate metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "transaction_date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txns")
        )
    
    # Calculate failure rate percentage
    merchant_performance_df = merchant_performance_df.withColumn(
        "failure_rate_pct", 
        (col("failed_txns") / col("txn_count") * 100).cast(DoubleType())
    )
    
    # Rename transaction_date to date and cast to timestamp
    merchant_performance_df = merchant_performance_df.withColumnRenamed("transaction_date", "date") \
       .withColumn("date", expr("to_timestamp(date)"))
    
    # Write to output path partitioned by date
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("status") == "COMPLETED")
    
    # Define schema for customer LTV
    customer_ltv_schema = StructType([
        StructField("customer_id", StringType(), True),
        StructField("total_spent", DoubleType(), True),
        StructField("total_txns", IntegerType(), True),
        StructField("avg_txn_value", DoubleType(), True),
        StructField("first_txn_date", TimestampType(), True),
        StructField("last_txn_date", TimestampType(), True),
        StructField("preferred_payment_method", StringType(), True)
    ])
    
    # Calculate metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
        .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            expr("AVG(amount)").alias("avg_txn_value"),
            min("transaction_timestamp").alias("first_txn_date"),
            max("transaction_timestamp").alias("last_txn_date")
        )
    
    # Determine preferred payment method (mode)
    from pyspark.sql.functions import collect_set, size, sort_array, first
    payment_method_counts = silver_df.groupBy("customer_id", "payment_method") \
       .agg(count("*").alias("count")) \
       .groupBy("customer_id") \
       .agg(collect_set(struct("payment_method", "count")).alias("payment_method_counts")) \
        .withColumn("payment_method_counts", sort_array(col("payment_method_counts"), ascending=False)) \
        .withColumn("preferred_payment_method", first(col("payment_method_counts.payment_method")))
    
    # Join with customer LTV DataFrame
    customer_ltv_df = customer_ltv_df.join(payment_method_counts, "customer_id", "left")
    
    # Write to output path
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Define schema for daily summary
    daily_summary_schema = StructType([
        StructField("date", TimestampType(), True),
        StructField("total_revenue", DoubleType(), True),
        StructField("total_txns", IntegerType(), True),
        StructField("unique_customers", IntegerType(), True),
        StructField("unique_merchants", IntegerType(), True),
        StructField("failure_rate_pct", DoubleType(), True)
    ])
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("transaction_date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id")).alias("unique_customers"),
            count(col("merchant_id")).alias("unique_merchants"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txns")
        )
    
    # Calculate failure rate percentage
    daily_summary_df = daily_summary_df.withColumn(
        "failure_rate_pct", 
        (col("failed_txns") / col("total_txns") * 100).cast(DoubleType())
    )
    
    # Rename transaction_date to date and cast to timestamp
    daily_summary_df = daily_summary_df.withColumnRenamed("transaction_date", "date") \
       .withColumn("date", expr("to_timestamp(date)"))
    
    # Write to output path partitioned by date
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths for each gold table
    merchant_performance_output_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_output_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_output_path = f"{gold_output_dir}/daily_summary"
    
    # Build gold tables
    build_merchant_performance(spark, silver_path, merchant_performance_output_path, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_output_path)
    build_daily_summary(spark, silver_path, daily_summary_output_path, run_date)
    
    # Write run metadata to JSON
    run_metadata = {
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "run_date": run_date,
        "tables_built": [
            "merchant_performance",
            "customer_ltv",
            "daily_summary"
        ]
    }
    
    spark.sparkContext.parallelize([run_metadata]).toDF().write.mode("overwrite").json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("GoldLayerPipeline").getOrCreate()
